version: 2

sources:
  - name: powerflow    #name of the source you will reference in the models
    database: powerflow #name of database
    schema: public
    tables:   #name all of the tables you would reference in the models
      - name: registrations
        description: Users registration data
        columns:
          - name: user_id
            description: Unique user id
          - name: registration_time
            description: Registration Timestamp
          - name: device_id
            description: User device id 
          - name: email
            description: User email
          - name: platform
            description: User's operation system or mobile platform 
          - name: country
            description: User's login country
      - name: appsflyer
      - name: google_ads
      - name: transactions
     